site_name: Autonomous Car Manager
repo_url: https://github.com/jbcodeforce/autonomous-car-mgr.git
site_author: Jerome Boyer
nav:
  - Introduction: index.md
theme: 
  name: material
  palette:
    scheme: default
  language: en
  features:
      - content.code.annotate
      - content.tooltips
      # - navigation.tabs
      - navigation.instant
      - navigation.tracking
      - navigation.footer
      # - navigation.sections
      # - navigation.expand
      - navigation.tabs.sticky
      # - navigation.top

  social:
    - type: 'github'
      link: 'https://github.com/jbcodeforce'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/jeromeboyer'
extra_css: ["extra.css"]
plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true